"""add job_analyses, applications, resume_versions, scraper_runs

Revision ID: 60db4ea0fa32
Revises: b65e79a73fb7
Create Date: 2026-06-20 01:28:40.344583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60db4ea0fa32'
down_revision: Union[str, Sequence[str], None] = 'b65e79a73fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tailored_resume_url', sa.String(), nullable=True),
    sa.Column('tailored_resume_text', sa.Text(), nullable=True),
    sa.Column('ats_score_before', sa.Integer(), nullable=True),
    sa.Column('ats_score_after', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ats_score', sa.Integer(), nullable=True),
    sa.Column('match_level', sa.String(), nullable=True),
    sa.Column('matching_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('missing_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('experience_match', sa.String(), nullable=True),
    sa.Column('visa_compatible', sa.Boolean(), nullable=True),
    sa.Column('visa_signal', sa.String(), nullable=True),
    sa.Column('visa_evidence', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version_type', sa.String(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('storage_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraper_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('jobs_found', sa.Integer(), nullable=True),
    sa.Column('jobs_new', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraper_runs')
    op.drop_table('resume_versions')
    op.drop_table('job_analyses')
    op.drop_table('applications')
    # ### end Alembic commands ###
